"""empty message

Revision ID: b04e44a8a300
Revises: 09219023e75f
Create Date: 2016-09-25 13:20:52.379042

"""

# revision identifiers, used by Alembic.
revision = 'b04e44a8a300'
down_revision = '09219023e75f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('content', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('created_time', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'created_time')
    op.drop_column('topics', 'content')
    ### end Alembic commands ###
