"""empty message

Revision ID: e1ed62d22dc4
Revises: None
Create Date: 2016-09-25 01:17:52.505759

"""

# revision identifiers, used by Alembic.
revision = 'e1ed62d22dc4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    ### end Alembic commands ###
