"""empty message

Revision ID: f6b318654bbb
Revises: b04e44a8a300
Create Date: 2016-09-25 15:28:09.356798

"""

# revision identifiers, used by Alembic.
revision = 'f6b318654bbb'
down_revision = 'b04e44a8a300'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('replys', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    ### end Alembic commands ###
